<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AssemblyVersion>0.0.2</AssemblyVersion>
        <FileVersion>0.0.2</FileVersion>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Google.Protobuf" Version="3.34.0" />
        <PackageReference Include="Grpc.Net.Client" Version="2.76.0" />
        <PackageReference Include="Grpc.Tools" Version="2.68.1">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.5" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Grpc\lightning.proto" GrpcServices="Client" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Models\Requests\" />
    </ItemGroup>

</Project>
